# Generated by Django 3.2.4 on 2021-06-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_game_fen_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='fen_line',
            field=models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR', max_length=100),
        ),
    ]
