# Generated by Django 3.2.4 on 2021-06-14 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_game_fen_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='fen_line',
        ),
        migrations.AddField(
            model_name='game',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='game_json',
            field=models.CharField(default='{"fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR"}', max_length=1000),
        ),
    ]
