# Generated by Django 3.2.4 on 2021-06-21 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game_json', models.CharField(default='{"fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR"}', max_length=1000)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
